# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: NPM install
      run: npm install

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        npm run build
        echo --------build finished!-------------
    - name: Set git config and deploy
      run: |
        env: 
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_USER: ${{ secrets.GH_USER }}
          PLANNER_GH_PAGES_ACCESS_TOKEN: ${{ secrets.PLANNER_GH_PAGES_ACCESS_TOKEN }}
        echo env $GH_EMAIL $GH_USER
        git config --global user.email $GH_EMAIL
        git config --global user.name $scerets.GH_USER }}
        git remote set-url origin https://$PLANNER_GH_PAGES_ACCESS_TOKEN@github.com/$GH_USER/projplanner.git 
        echo starting deploy....
        npm run deploy
    
      
